# Generated by Django 4.2.7 on 2023-12-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_place',
            field=models.CharField(default='US', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='working_as',
            field=models.CharField(default='Freelancer', max_length=30),
            preserve_default=False,
        ),
    ]
