# Generated by Django 4.2.7 on 2023-12-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
